export const maastikud = [
    "Haanja kõrgustik",
    "Harju lavamaa",
    "Karula kõrgustik",
    "Kesk-Eesti tasandik",
    "Lääne-Eesti madalik",
    "Otepää kõrgustik",
    "Pandivere kõrgustik",
    "Peipsi madalik",
    "Pärnu madalik",
    "Sakala kõrgustik",
    ["Ugandi lavamaa", "Kagu Eesti lavamaa"],
    "Vooremaa",
    "Võrtsjärve madalik",
];

export const saared = [
    "Abruka",
    "Haapsalu laht",
    "Hara laht",
    "Hari kurk",
    "Hiiumaa",
    "Juminda poolsaar",
    "Kassari poolsaar",
    "Kihnu väin",
    "Kihnu",
    "Kolga laht",
    "Kunda laht",
    ["Kura kurk", "Irbe väin"],
    "Kõpu poolsaar",
    "Liivi laht",
    "Mardihansu laht",
    "Matsalu laht",
    "Muhu",
    "Naissaar",
    "Narva laht",
    "Noarootsi poolsaar",
    "Osmussaar",
    "Pakri poolsaar",
    "Paldiski laht",
    "Piirissaar",
    "Prangli",
    "Pärispea poolsaar",
    "Pärnu laht",
    "Ruhnu",
    "Saaremaa",
    "Soela väin",
    "Soome laht",
    "Suur Katel",
    "Suur väin",
    "Suur-Pakri",
    "Sõrve poolsaar",
    "Tagamõisa poolsaar",
    "Tallinna laht",
    "Viimsi poolsaar",
    "Vilsandi",
    "Voosi kurk",
    "Vormsi",
    "Väike väin",
    "Väike-Pakri",
    "Väinameri",
]

export const veekogud = [
    "Ahja jõgi",
    "Elva jõgi",
    "Endla järv",
    "Ermistu järv",
    "Halliste jõgi",
    "Jägala jõgi",
    "Kahala järv",
    "Karujärv",
    "Kasari jõgi",
    "Keila jõgi",
    "Koosa järv",
    "Kunda jõgi",
    "Kuremaa järv",
    "Mullutu laht",
    "Narva jõgi",
    "Narva veehoidla",
    "Navesti jõgi",
    "Paunküla veehoidla",
    "Pedja jõgi",
    "Peipsi järv",
    "Pirita jõgi",
    "Piusa jõgi",
    "Pärnu jõgi",
    "Põltsamaa jõgi",
    "Pühajärv",
    "Raudna jõgi",
    "Saadjärv",
    "Sauga jõgi",
    ["Sutlepa meri", "Sutlepa järv"],
    "Suur Emajõgi",
    "Suurlaht",
    "Tõhela järv",
    "Vagula järv",
    "Valgejõgi",
    "Veisjärv",
    "Vigala jõgi",
    "Väike-Emajõgi",
    "Võhandu jõgi",
    "Võrtsjärv",
    "Õhne jõgi",
    "Ülemiste järv",
];