<script lang="ts">
    import Map from "$lib/map.svelte";

    const waters = [
        "Ahja jõgi",
        "Elva jõgi",
        "Endla järv",
        "Ermistu järv",
        "Halliste jõgi",
        "Jägala jõgi",
        "Kahala järv",
        "Karujärv",
        "Kassari jõgi",
        "Keila jõgi",
        "Koosa järv",
        "Kunda jõgi",
        "Kuremaa järv",
        "Mullutu-Suurlaht",
        "Narva jõgi",
        "Narva veehoidla",
        "Navesti jõgi",
        "Õhne jõgi",
        "Pärnu jõgi",
        "Paunküla veehoidla",
        "Pedja jõgi",
        "Peipsi järv",
        "Pirita jõgi",
        "Piusa jõgi",
        "Põltsamaa jõgi",
        "Pühajärv",
        "Purtse jõgi",
        "Raudna jõgi",
        "Saadjärv",
        "Sauga jõgi",
        "Sutlepa meri",
        "Suur Emajõgi",
        "Suurlaht",
        "Tamula järv",
        "Tõhela järv",
        "Ülemiste järv",
        "Vagula järv",
        "Väike-Emajõgi",
        "Valgejõgi",
        "Veisjärv",
        "Vigala jõgi",
        "Võhandu jõgi",
        "Võrtsjärv",
    ];
</script>

<Map path="veekogud" names={waters} />
