<script lang="ts">
    import Map from "$lib/map.svelte";

    const islands = [
        "Abruka",
        "Haapsalu laht",
        "Hara laht",
        "Hari kurk",
        "Hiiumaa",
        "Juminda poolsaar",
        "Kassari",
        "Kihnu väin",
        "Kihnu",
        "Kolga laht",
        "Kõpu poolsaar",
        "Kunda laht",
        "Kura kurk",
        "Liivi laht",
        "Mardihansu laht",
        "Matsalu laht",
        "Muhu",
        "Naissaar",
        "Narva laht",
        "Noarootsi poolsaar",
        "Osmussaar",
        "Pakri poolsaar",
        "Paldiski laht",
        "Pärispea poolsaar",
        "Pärnu laht",
        "Piirissaar",
        "Prangli saar",
        "Ruhnu",
        "Saaremaa",
        "Soela väin",
        "Soome laht",
        "Sõrve poolsaar",
        "Suur Katel",
        "Suur väin",
        "Suur-Pakri",
        "Tagamõisa poolsaar",
        "Tallinna laht",
        "Väike väin",
        "Väike-Pakri",
        "Väinameri",
        "Viimsi poolsaar",
        "Vilsandi",
        "Voosi kurk",
        "Vormsi",
    ];
</script>

<Map path="saared" names={islands} />
